// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage;
using Microsoft.EntityFrameworkCore.Storage.Internal;
using System;
using TodoAPI_CRUD.Models;

namespace TodoAPI_CRUD.Migrations
{
    [DbContext(typeof(ApplicationContext))]
    partial class ApplicationContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.0.2-rtm-10011")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Abonnements", b =>
                {
                    b.Property<long>("ID")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abonnement");

                    b.Property<DateTime>("DateDebut");

                    b.Property<DateTime>("DateFin");

                    b.Property<long>("PKAbonnement");

                    b.Property<long>("PkAbonne");

                    b.Property<long>("Prix_Abonnement");

                    b.HasKey("ID");

                    b.ToTable("Abonnements");
                });

            modelBuilder.Entity("FichierCentral", b =>
                {
                    b.Property<long>("PK")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Abonnement")
                        .IsRequired();

                    b.Property<DateTime>("DateCreation");

                    b.Property<string>("Email")
                        .IsRequired();

                    b.Property<string>("Login")
                        .IsRequired();

                    b.Property<string>("Nom")
                        .IsRequired();

                    b.Property<int>("PkAbonnemnt");

                    b.Property<int>("PkCategorieAbonnement");

                    b.Property<int>("PkProfil");

                    b.Property<string>("Prenom")
                        .IsRequired();

                    b.Property<Guid>("UserId");

                    b.HasKey("PK");

                    b.ToTable("FichierCentral");
                });
#pragma warning restore 612, 618
        }
    }
}
